#pragma once

#ifndef CODRIVER_TEST_ENABLE_NON_HW
#define CODRIVER_TEST_ENABLE_NON_HW 0
#endif

#ifndef CODRIVER_TEST_ENABLE_HW
#define CODRIVER_TEST_ENABLE_HW 0
#endif

#ifndef CODRIVER_TEST_ENABLE_HW_SENSORS
#define CODRIVER_TEST_ENABLE_HW_SENSORS 0
#endif

#ifndef CODRIVER_TEST_ENABLE_OBDII
#define CODRIVER_TEST_ENABLE_OBDII 0
#endif

#ifndef CODRIVER_TEST_ENABLE_SCREEN
#define CODRIVER_TEST_ENABLE_SCREEN 1
#endif